services:

  keycloak:
    build: ./keycloak
    container_name: bel-keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

  backend:
    build: ./backend
    container_name: bel-backend
    ports:
      - "4000:4000"
    depends_on:
      - keycloak
    env_file:
      - ./backend/.env.docker

  frontend:
    build: ./frontend
    container_name: bel-frontend
    ports:
      - "5173:4173"
    depends_on:
      - backend